# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wN397wZweX1_lJjtJErD-qJZn5Uo8cAH
"""

import streamlit as st
import pandas as pd
import joblib

def main():
    # Set the page configuration
    st.set_page_config(page_title="Professor Salary Predictor", layout="centered")

    # Title and description
    st.title("🎓 Professor Salary Predictor")
    st.write("Enter the details below to predict the professor's salary.")

    # Load the trained model
    # Ensure 'trained_model.joblib' is in the same directory as this script
    try:
        model = joblib.load('trained_model.joblib')
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return

    # Create two columns for layout
    col1, col2 = st.columns(2)

    with col1:
        # Input: Rank
        # Values derived from your dataset: ['Prof', 'AssocProf', 'AsstProf']
        rank = st.selectbox("Rank", options=['Prof', 'AssocProf', 'AsstProf'])

        # Input: PhD (Years since PhD)
        phd = st.number_input("Years since PhD", min_value=0, max_value=70, value=20, step=1)

        # Input: Sex
        # Values derived from your dataset: ['Male', 'Female']
        sex = st.selectbox("Sex", options=['Male', 'Female'])

    with col2:
        # Input: Discipline
        # Values derived from your dataset: ['A', 'B']
        discipline = st.selectbox("Discipline", options=['A', 'B'])

        # Input: Service (Years of Service)
        service = st.number_input("Years of Service", min_value=0, max_value=70, value=15, step=1)

    # Add a predict button
    if st.button("Predict Salary"):
        # Create a DataFrame from the inputs
        # The column names must match exactly what the model was trained on
        input_data = pd.DataFrame({
            'rank': [rank],
            'discipline': [discipline],
            'phd': [phd],
            'service': [service],
            'sex': [sex]
        })

        # Make prediction
        try:
            prediction = model.predict(input_data)
            salary = prediction[0]

            # Display result
            st.success(f"### Predicted Salary: ${salary:,.2f}")

            # Optional: Show the input data used for prediction
            with st.expander("See input data"):
                st.dataframe(input_data)

        except Exception as e:
            st.error(f"Error making prediction: {e}")

if __name__ == '__main__':
    main()